[project]
name = "cerebellum"
version = "0.1.0"
description = "Cognitive architecture for AI agents"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "axonium>=0.6.0",
]

[project.optional-dependencies]
llama = [
  "axonium>=0.6.0",
]

[tool.setuptools.packages.find]
where = ["src"]
